Public Class Weather
    <Serializable()> _
    Public Class WeatherCondition
        Public Value As String
        Public Location As String
        Public ItsType As Boolean
        Public Warning As Boolean
        Public Day As Boolean
        Public TimeBased As Boolean
        Public Indefinite As Boolean
        Public Sub New(ByVal SValue As String, ByVal SLocation As String, ByVal SItsType As Boolean, ByVal SWarning As Boolean, ByVal SDay As Boolean, ByVal STimeBased As Boolean, ByVal SIndefinite As Boolean)
            Me.Value = SValue
            Me.Location = SLocation
            Me.ItsType = SItsType
            Me.Warning = SWarning
            Me.Day = SDay
            Me.TimeBased = STimeBased
            Me.Indefinite = SIndefinite
        End Sub
    End Class

    Public Shared Function GetConditions(ByVal Forcast As pWeatherForecast) As WeatherCondition
        Dim Value As String = ""
        Dim ItsType As Boolean
        Dim Warning As Boolean
        Dim Day As Boolean
        Dim TimeBased As Boolean
        Dim Indefinite As Boolean = False
        Dim ConditionCode As Integer = Forcast.rss.channel.item.condition.code
        If ConditionCode = 0 Then
            Value = "Tornado"
            ItsType = False
            Warning = True
            Day = True
            TimeBased = False
            Indefinite = True
        ElseIf ConditionCode = 1 Then
            Value = "Tropical Storm"
            ItsType = False
            Warning = True
            Day = True
            TimeBased = False
            Indefinite = True
        ElseIf ConditionCode = 2 Then
            Value = "Hurricane"
            ItsType = False
            Warning = True
            Day = True
            TimeBased = False
            Indefinite = True
        ElseIf ConditionCode = 3 Then
            Value = "Severe Thunderstorm"
            ItsType = False
            Warning = True
            Day = True
            TimeBased = False
            Indefinite = True
        ElseIf ConditionCode = 4 Then
            Value = "Thunderstorm"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
            Indefinite = True
        ElseIf ConditionCode = 5 Then
            Value = "Mixed Rain and Snow"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 6 Then
            Value = "Mixed Rain and Sleet"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 7 Then
            Value = "Mixed Snow and Sleet"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 8 Then
            Value = "Freezing Drizzle"
            ItsType = False
            Warning = False
        ElseIf ConditionCode = 9 Then
            Value = "Drizzling"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 10 Then
            Value = "Freezing Rain"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 11 Then
            Value = "Showers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 12 Then
            Value = "Showers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 13 Then
            Value = "Snow Flurries"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 14 Then
            Value = "Light Snow Showers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 15 Then
            Value = "Blowing Snow"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 16 Then
            Value = "Snow"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 17 Then
            Value = "Hail"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 18 Then
            Value = "Sleet"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 19 Then
            Value = "Dusty"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 20 Then
            Value = "Foggy"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 21 Then
            Value = "Hazy"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 22 Then
            Value = "Smoky"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 23 Then
            Value = "Blustery"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 24 Then
            Value = "Windy"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 25 Then
            Value = "Cold"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 26 Then
            Value = "Cloudy"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 27 Then
            Value = "Mostly Cloudy"
            ItsType = True
            Warning = False
            Day = False
            TimeBased = True
        ElseIf ConditionCode = 28 Then
            Value = "Mostly Cloudy"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = True
        ElseIf ConditionCode = 29 Then
            Value = "Partly Cloudy"
            ItsType = True
            Warning = False
            Day = False
            TimeBased = True
        ElseIf ConditionCode = 30 Then
            Value = "Partly Cloudy"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = True
        ElseIf ConditionCode = 31 Then
            Value = "Clear"
            ItsType = True
            Warning = False
            Day = False
            TimeBased = True
        ElseIf ConditionCode = 32 Then
            Value = "Sunny"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = True
        ElseIf ConditionCode = 33 Then
            Value = "Fair"
            ItsType = True
            Warning = False
            Day = False
            TimeBased = True
        ElseIf ConditionCode = 34 Then
            Value = "Fair"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = True
        ElseIf ConditionCode = 35 Then
            Value = "Mixed Rain and Hail"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 36 Then
            Value = "Hot"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 37 Then
            Value = "Isolated Thunderstorms"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 38 Then
            Value = "Scattered Thunderstorms"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 39 Then
            Value = "Scattered Thunderstorms"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 40 Then
            Value = "Scattered Showers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 41 Then
            Value = "Heavy Snow"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 42 Then
            Value = "Scattered Snow Showers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 43 Then
            Value = "Heavy Snow"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 44 Then
            Value = "Partly Cloudy"
            ItsType = True
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 45 Then
            Value = "Thundershowers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 46 Then
            Value = "Snow Showers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 47 Then
            Value = "Isolated Thundershowers"
            ItsType = False
            Warning = False
            Day = True
            TimeBased = False
        ElseIf ConditionCode = 3200 Then
            Value = "Unavailable"
            ItsType = False
            Warning = False
            Day = False
            TimeBased = False
        End If
        GetConditions = New WeatherCondition(Value, Forcast.rss.channel.location.city, ItsType, Warning, Day, TimeBased, Indefinite)
    End Function
    Public Shared Function GetConditionsWithDescription(ByVal Conditons As WeatherCondition) As String
        Dim ConditonsDescription As String = ""
        Dim ConditonName As String = Conditons.Value.ToLower
        Dim Article As String
        Dim Warning As String
        If Conditons.Indefinite = True Then
            Article = "a "
        Else
            Article = ""
        End If
        If Conditons.Warning = True Then
            Warning = " warning"
        Else
            Warning = ""
        End If
        If Conditons.ItsType = False Then
            ConditonsDescription = String.Format("There's {0}{1}{2} in {3}.", Article, ConditonName, Warning, Conditons.Location)
        Else
            ConditonsDescription = String.Format("It's {0}{1}{2} in {3}.", Article, ConditonName, Warning, Conditons.Location)
        End If
        If ConditonName = "Unabailable" Then
            ConditonsDescription = "The weather is unabailable for your location."
        End If
        GetConditionsWithDescription = ConditonsDescription
    End Function
End Class
